######## Gain ########
# by gyro
foot_roll_gyro_p_gain : 0.0 #0.6
foot_roll_gyro_d_gain : 0.0

foot_pitch_gyro_p_gain : 0.0 #0.6
foot_pitch_gyro_d_gain : 0.0

# by imu
foot_roll_angle_p_gain : 0.0 #1.2
foot_roll_angle_d_gain : 0.0

foot_pitch_angle_p_gain : 0.0 #1.2
foot_pitch_angle_d_gain : 0.0

# by ft sensor
foot_x_force_p_gain : 0.0 #0.25
foot_x_force_d_gain : 0.0

foot_y_force_p_gain : 0.0 #0.25
foot_y_force_d_gain : 0.0

foot_z_force_p_gain : 0.0 #0.04
foot_z_force_d_gain : 0.0

foot_roll_torque_p_gain : 0.0 #0.002
foot_roll_torque_d_gain : 0.0

foot_pitch_torque_p_gain : 0.0 #0.002
foot_pitch_torque_d_gain : 0.0

######## CUT OFF FREQUENCY ########
# by gyro
roll_gyro_cut_off_frequency  : 10.0
pitch_gyro_cut_off_frequency : 10.0

# by imu
roll_angle_cut_off_frequency  : 10.0
pitch_angle_cut_off_frequency : 10.0

# by ft sensor
foot_x_force_cut_off_frequency : 5.0
foot_y_force_cut_off_frequency : 5.0
foot_z_force_cut_off_frequency : 1.0
foot_roll_torque_cut_off_frequency : 5.0
foot_pitch_torque_cut_off_frequency : 5.0
