r_leg_hip_y_p_gain : 0.0 #0.5
r_leg_hip_y_d_gain : 0.0

r_leg_hip_r_p_gain : 0.0 #0.75
r_leg_hip_r_d_gain : 0.0

r_leg_hip_p_p_gain : 0.0 #0.075
r_leg_hip_p_d_gain : 0.0

r_leg_kn_p_p_gain  : 0.0 #0.075
r_leg_kn_p_d_gain  : 0.0

r_leg_an_p_p_gain  : 0.0 #0.025
r_leg_an_p_d_gain  : 0.0

r_leg_an_r_p_gain  : 0.0 #0.025
r_leg_an_r_d_gain  : 0.0


l_leg_hip_y_p_gain : 0.0 #0.5
l_leg_hip_y_d_gain : 0.0

l_leg_hip_r_p_gain : 0.0 #0.75
l_leg_hip_r_d_gain : 0.0

l_leg_hip_p_p_gain : 0.0 #0.075
l_leg_hip_p_d_gain : 0.0

l_leg_kn_p_p_gain  : 0.0 #0.075
l_leg_kn_p_d_gain  : 0.0

l_leg_an_p_p_gain  : 0.0 #0.025
l_leg_an_p_d_gain  : 0.0

l_leg_an_r_p_gain  : 0.0 #0.025
l_leg_an_r_d_gain  : 0.0
