# 1.0 -> 1 [deg]

r_leg_hip_y_gain : 0.0
r_leg_hip_r_gain : 0.0 #5.0
r_leg_hip_p_gain : 0.0
r_leg_kn_p_gain  : 0.0
r_leg_an_p_gain  : 0.0
r_leg_an_r_gain  : 0.0

l_leg_hip_y_gain : 0.0
l_leg_hip_r_gain : 0.0 #-5.0
l_leg_hip_p_gain : 0.0
l_leg_kn_p_gain  : 0.0
l_leg_an_p_gain  : 0.0
l_leg_an_r_gain  : 0.0
